### ISSUE TITLE
Test failure because test uses theloop.co.kr git repo

### ISSUE THREAD

**Issue by Meai** [theloopkr/loopchain#11]
Of course I dont have any keys for this repo: `git@repo.theloop.co.kr:score/chain_message_score.git`
```

ERROR: setUpClass (test_score_deploy.TestScoreDeploy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pc/loopchain/testcase/unittest/test_score_deploy.py", line 49, in setUpClass
    cls.__repo = Repo.clone_from(cls.__repo_url, cls.__repository_path, branch='master')
  File "/home/pc/loopchain/lib/python3.6/site-packages/git/repo/base.py", line 982, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/home/pc/loopchain/lib/python3.6/site-packages/git/repo/base.py", line 933, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/pc/loopchain/lib/python3.6/site-packages/git/util.py", line 336, in finalize_process
    proc.wait(**kwargs)
  File "/home/pc/loopchain/lib/python3.6/site-packages/git/cmd.py", line 418, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --branch=master -v git@repo.theloop.co.kr:score/chain_message_score.git /home/pc/loopchain/resources/test_score_deploy/score/chain_message_score
  stderr: 'Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by jinhoyoo** [comment]
@BK-winDy-theloop , Please follow up this issue. @Meai, can I get your mail address to contact?

**Comment by Meai** [comment]
Yeah but I dont see why not just respond here, I'm just a random person. I made my email visible in my profile now. I also posted a question on reddit btw, I was curious about whether ICON has something like an ERC20 standard.

**Comment by BK-winDy-theloop** [comment]
This test is not for open source.
It is a test for our closed network.
There was a mistake.
We will fix it.

**Comment by herskinduk** [comment]
Please reopen this issue and close it once you have fixed the issue. The issue is still in master branch.
